apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- service.yaml
- statefulset.yaml
- envoy-filter.yaml
- pvc.yaml

namespace: istio-system

configMapGenerator:
- envs:
  - params.env
  name: oidc-authservice-parameters
secretGenerator:
- envs:
  - secret_params.env
  name: oidc-authservice-client-info

vars:
- fieldref:
    fieldpath: metadata.namespace
  name: NAMESPACE
  objref:
    apiVersion: v1
    kind: Service
    name: authservice
configurations:
- params.yaml
images:
- name: gcr.io/arrikto/kubeflow/oidc-authservice
  newName: gcr.io/arrikto-public/kubeflow/oidc-authservice
  newTag: 0c0b57b
